name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t dlaawork9888/dlawork9888site:latest .
          docker push dlaawork9888/dlawork9888site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 만약 컨테이너가 3000번 포트에서 실행되고 있다면, 이를 이용해 컨테이너 ID를 찾고 종료
            CONTAINER_ID=$(sudo docker ps -q -f "publish=3000")
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            # Pull the latest Docker image
            sudo docker pull dlaawork9888/dlawork9888site:latest

            # Run the new container
            sudo docker run -d --name dlawork9888sitedeployedbygithubaction -p 3000:3000 dlaawork9888/dlawork9888site:latest
